// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui/ui.h"
#include "ui/ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_main_screen
void ui_main_screen_screen_init(void);
lv_obj_t *ui_main_screen;
lv_obj_t *ui_main_panel;
lv_obj_t *ui_clock_panel;
lv_obj_t *ui_date_label;
lv_obj_t *ui_time_label;
lv_obj_t *ui_weather_panel;
lv_obj_t *ui_weather1;
lv_obj_t *ui_weather1_hour;
lv_obj_t *ui_weather1_icon;
lv_obj_t *ui_weather1_temperature;
lv_obj_t *ui_weather2;
lv_obj_t *ui_weather2_hour;
lv_obj_t *ui_weather2_icon;
lv_obj_t *ui_weather2_temperature;
lv_obj_t *ui_weather3;
lv_obj_t *ui_weather3_hour;
lv_obj_t *ui_weather3_icon;
lv_obj_t *ui_weather3_temperature;
lv_obj_t *ui_weather4;
lv_obj_t *ui_weather4_hour;
lv_obj_t *ui_weather4_icon;
lv_obj_t *ui_weather4_temperature;
lv_obj_t *ui_weather5;
lv_obj_t *ui_weather5_hour;
lv_obj_t *ui_weather5_icon;
lv_obj_t *ui_weather5_temperature;
lv_obj_t *ui_schedule_panel;
lv_obj_t *ui_schedule1;
lv_obj_t *ui_schedule1_busnumber1;
lv_obj_t *ui_schedule1_destination1;
lv_obj_t *ui_schedule1_time1;
lv_obj_t *ui_schedule2;
lv_obj_t *ui_schedule2_busnumber;
lv_obj_t *ui_schedule2_destination;
lv_obj_t *ui_schedule2_time;
lv_obj_t *ui_schedule3;
lv_obj_t *ui_schedule3_busnumber;
lv_obj_t *ui_schedule3_destination;
lv_obj_t *ui_schedule3_time;
lv_obj_t *ui_schedule4;
lv_obj_t *ui_schedule4_busnumber;
lv_obj_t *ui_schedule4_destination;
lv_obj_t *ui_schedule4_time;
lv_obj_t *ui_schedule5;
lv_obj_t *ui_schedule5_busnumber;
lv_obj_t *ui_schedule5_destination;
lv_obj_t *ui_schedule5_time;

// SCREEN: ui_init_screen
void ui_init_screen_screen_init(void);
lv_obj_t *ui_init_screen;
lv_obj_t *ui_init_screen_spinner;
lv_obj_t *ui_init_screen_label;
lv_obj_t *ui____initial_actions0;

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_screen_init();
    ui_init_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_init_screen);
}
