// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui/ui.h"

void ui_main_screen_screen_init(void)
{
  ui_main_screen = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_main_screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_main_panel = lv_obj_create(ui_main_screen);
  lv_obj_set_width(ui_main_panel, lv_pct(100));
  lv_obj_set_height(ui_main_panel, lv_pct(100));
  lv_obj_set_x(ui_main_panel, -1);
  lv_obj_set_y(ui_main_panel, 0);
  lv_obj_set_align(ui_main_panel, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_main_panel, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_main_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_main_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_border_width(ui_main_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_main_panel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_main_panel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_main_panel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_main_panel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_main_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_main_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_clock_panel = lv_obj_create(ui_main_panel);
  lv_obj_set_height(ui_clock_panel, 77);
  lv_obj_set_width(ui_clock_panel, lv_pct(100));
  lv_obj_set_x(ui_clock_panel, 1);
  lv_obj_set_y(ui_clock_panel, -14);
  lv_obj_set_align(ui_clock_panel, LV_ALIGN_TOP_MID);
  lv_obj_set_flex_flow(ui_clock_panel, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_clock_panel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_clock_panel, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_pad_left(ui_clock_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_clock_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_clock_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_clock_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_date_label = lv_label_create(ui_clock_panel);
  lv_obj_set_width(ui_date_label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_date_label, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_date_label, 27);
  lv_obj_set_y(ui_date_label, -104);
  lv_obj_set_align(ui_date_label, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_date_label, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_date_label, "lauantai\n23.9.");
  lv_obj_set_style_text_align(ui_date_label, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_date_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_date_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_date_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_date_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_date_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_time_label = lv_label_create(ui_clock_panel);
  lv_obj_set_width(ui_time_label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_time_label, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_time_label, -39);
  lv_obj_set_y(ui_time_label, -81);
  lv_obj_set_align(ui_time_label, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_time_label, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_time_label, "13:12");
  lv_obj_set_style_text_align(ui_time_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_time_label, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather_panel = lv_obj_create(ui_main_panel);
  lv_obj_set_height(ui_weather_panel, 75);
  lv_obj_set_width(ui_weather_panel, lv_pct(100));
  lv_obj_set_x(ui_weather_panel, 0);
  lv_obj_set_y(ui_weather_panel, -34);
  lv_obj_set_align(ui_weather_panel, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_weather_panel, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_weather_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
  lv_obj_clear_flag(ui_weather_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_pad_left(ui_weather_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_weather_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_weather_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather1 = lv_obj_create(ui_weather_panel);
  lv_obj_set_height(ui_weather1, lv_pct(100));
  lv_obj_set_flex_grow(ui_weather1, 1);
  lv_obj_set_align(ui_weather1, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_weather1, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_weather1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_weather1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_weather1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_weather1, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_opa(ui_weather1, 255, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_width(ui_weather1, 1, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_spread(ui_weather1, 0, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_x(ui_weather1, -2, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_y(ui_weather1, 0, LV_PART_MAIN | LV_STATE_USER_1);

  lv_obj_set_style_radius(ui_weather1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_weather1_hour = lv_label_create(ui_weather1);
  lv_obj_set_width(ui_weather1_hour, lv_pct(100));
  lv_obj_set_height(ui_weather1_hour, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather1_hour, LV_ALIGN_CENTER);
  lv_label_set_text(ui_weather1_hour, "15");
  lv_obj_set_style_text_color(ui_weather1_hour, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather1_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather1_hour, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_weather1_hour, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_weather1_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_weather1_hour, lv_color_hex(0xE7F0FA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_weather1_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather1_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather1_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather1_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather1_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather1_icon = lv_img_create(ui_weather1);
  lv_img_set_src(ui_weather1_icon, &icon_1);
  lv_obj_set_width(ui_weather1_icon, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather1_icon, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_weather1_icon, 7);
  lv_obj_set_y(ui_weather1_icon, -29);
  lv_obj_set_align(ui_weather1_icon, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_weather1_icon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_weather1_icon, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_weather1_temperature = lv_label_create(ui_weather1);
  lv_obj_set_width(ui_weather1_temperature, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather1_temperature, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather1_temperature, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_weather1_temperature, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_weather1_temperature, "17°");
  lv_obj_set_style_text_color(ui_weather1_temperature, lv_color_hex(0xE00000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather1_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather1_temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather2 = lv_obj_create(ui_weather_panel);
  lv_obj_set_height(ui_weather2, lv_pct(100));
  lv_obj_set_flex_grow(ui_weather2, 1);
  lv_obj_set_align(ui_weather2, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_weather2, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_weather2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_weather2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_weather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_weather2, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_opa(ui_weather2, 255, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_width(ui_weather2, 1, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_spread(ui_weather2, 0, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_x(ui_weather2, -2, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_y(ui_weather2, 0, LV_PART_MAIN | LV_STATE_USER_1);

  lv_obj_set_style_radius(ui_weather2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_weather2_hour = lv_label_create(ui_weather2);
  lv_obj_set_width(ui_weather2_hour, lv_pct(100));
  lv_obj_set_height(ui_weather2_hour, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather2_hour, LV_ALIGN_CENTER);
  lv_label_set_text(ui_weather2_hour, "18");
  lv_obj_set_style_text_color(ui_weather2_hour, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather2_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather2_hour, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_weather2_hour, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_weather2_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_weather2_hour, lv_color_hex(0xE7F0FA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_weather2_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather2_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather2_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather2_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather2_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather2_icon = lv_img_create(ui_weather2);
  lv_img_set_src(ui_weather2_icon, &icon_1);
  lv_obj_set_width(ui_weather2_icon, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather2_icon, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_weather2_icon, 7);
  lv_obj_set_y(ui_weather2_icon, -29);
  lv_obj_set_align(ui_weather2_icon, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_weather2_icon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_weather2_icon, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_weather2_temperature = lv_label_create(ui_weather2);
  lv_obj_set_width(ui_weather2_temperature, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather2_temperature, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather2_temperature, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_weather2_temperature, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_weather2_temperature, "16°");
  lv_obj_set_style_text_color(ui_weather2_temperature, lv_color_hex(0xE00000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather2_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather2_temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather3 = lv_obj_create(ui_weather_panel);
  lv_obj_set_height(ui_weather3, lv_pct(100));
  lv_obj_set_flex_grow(ui_weather3, 1);
  lv_obj_set_align(ui_weather3, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_weather3, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_weather3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_weather3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_weather3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_weather3, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_opa(ui_weather3, 255, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_width(ui_weather3, 1, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_spread(ui_weather3, 0, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_x(ui_weather3, -2, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_y(ui_weather3, 0, LV_PART_MAIN | LV_STATE_USER_1);

  lv_obj_set_style_radius(ui_weather3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_weather3_hour = lv_label_create(ui_weather3);
  lv_obj_set_width(ui_weather3_hour, lv_pct(100));
  lv_obj_set_height(ui_weather3_hour, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather3_hour, LV_ALIGN_CENTER);
  lv_label_set_text(ui_weather3_hour, "21");
  lv_obj_set_style_text_color(ui_weather3_hour, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather3_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather3_hour, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_weather3_hour, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_weather3_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_weather3_hour, lv_color_hex(0xE7F0FA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_weather3_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather3_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather3_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather3_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather3_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather3_icon = lv_img_create(ui_weather3);
  lv_img_set_src(ui_weather3_icon, &icon_1);
  lv_obj_set_width(ui_weather3_icon, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather3_icon, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_weather3_icon, 7);
  lv_obj_set_y(ui_weather3_icon, -29);
  lv_obj_set_align(ui_weather3_icon, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_weather3_icon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_weather3_icon, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_weather3_temperature = lv_label_create(ui_weather3);
  lv_obj_set_width(ui_weather3_temperature, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather3_temperature, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather3_temperature, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_weather3_temperature, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_weather3_temperature, "16°");
  lv_obj_set_style_text_color(ui_weather3_temperature, lv_color_hex(0xE00000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather3_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather3_temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather4 = lv_obj_create(ui_weather_panel);
  lv_obj_set_height(ui_weather4, lv_pct(100));
  lv_obj_set_flex_grow(ui_weather4, 1);
  lv_obj_set_align(ui_weather4, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_weather4, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_weather4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_weather4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_weather4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_weather4, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_opa(ui_weather4, 255, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_width(ui_weather4, 1, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_spread(ui_weather4, 0, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_x(ui_weather4, -2, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_y(ui_weather4, 0, LV_PART_MAIN | LV_STATE_USER_1);

  ui_weather4_hour = lv_label_create(ui_weather4);
  lv_obj_set_width(ui_weather4_hour, lv_pct(100));
  lv_obj_set_height(ui_weather4_hour, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather4_hour, LV_ALIGN_CENTER);
  lv_label_set_text(ui_weather4_hour, "00");
  lv_obj_set_style_text_color(ui_weather4_hour, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather4_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather4_hour, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_weather4_hour, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_weather4_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_weather4_hour, lv_color_hex(0xE7F0FA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_weather4_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather4_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather4_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather4_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather4_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather4_icon = lv_img_create(ui_weather4);
  lv_img_set_src(ui_weather4_icon, &icon_1);
  lv_obj_set_width(ui_weather4_icon, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather4_icon, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_weather4_icon, 7);
  lv_obj_set_y(ui_weather4_icon, -29);
  lv_obj_set_align(ui_weather4_icon, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_weather4_icon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_weather4_icon, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_weather4_temperature = lv_label_create(ui_weather4);
  lv_obj_set_width(ui_weather4_temperature, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather4_temperature, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather4_temperature, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_weather4_temperature, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_weather4_temperature, "15°");
  lv_obj_set_style_text_color(ui_weather4_temperature, lv_color_hex(0xE00000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather4_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather4_temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather5 = lv_obj_create(ui_weather_panel);
  lv_obj_set_height(ui_weather5, lv_pct(100));
  lv_obj_set_flex_grow(ui_weather5, 1);
  lv_obj_set_align(ui_weather5, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_weather5, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_weather5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_weather5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_weather5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_weather5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_weather5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_weather5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_weather5, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_opa(ui_weather5, 255, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_width(ui_weather5, 1, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_spread(ui_weather5, 0, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_x(ui_weather5, -2, LV_PART_MAIN | LV_STATE_USER_1);
  lv_obj_set_style_shadow_ofs_y(ui_weather5, 0, LV_PART_MAIN | LV_STATE_USER_1);

  lv_obj_set_style_radius(ui_weather5, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

  ui_weather5_hour = lv_label_create(ui_weather5);
  lv_obj_set_width(ui_weather5_hour, lv_pct(100));
  lv_obj_set_height(ui_weather5_hour, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather5_hour, LV_ALIGN_CENTER);
  lv_label_set_text(ui_weather5_hour, "03");
  lv_obj_set_style_text_color(ui_weather5_hour, lv_color_hex(0x303193), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather5_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather5_hour, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_weather5_hour, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_weather5_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_weather5_hour, lv_color_hex(0xE7F0FA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_weather5_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_weather5_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_weather5_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_weather5_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_weather5_hour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_weather5_icon = lv_img_create(ui_weather5);
  lv_img_set_src(ui_weather5_icon, &icon_1);
  lv_obj_set_width(ui_weather5_icon, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather5_icon, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_weather5_icon, 7);
  lv_obj_set_y(ui_weather5_icon, -29);
  lv_obj_set_align(ui_weather5_icon, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_weather5_icon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  lv_obj_clear_flag(ui_weather5_icon, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_weather5_temperature = lv_label_create(ui_weather5);
  lv_obj_set_width(ui_weather5_temperature, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_weather5_temperature, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_weather5_temperature, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_weather5_temperature, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_weather5_temperature, "15°");
  lv_obj_set_style_text_color(ui_weather5_temperature, lv_color_hex(0xE00000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_weather5_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_weather5_temperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule_panel = lv_obj_create(ui_main_panel);
  lv_obj_set_width(ui_schedule_panel, lv_pct(100));
  lv_obj_set_flex_grow(ui_schedule_panel, 1);
  lv_obj_set_align(ui_schedule_panel, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_schedule_panel, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_schedule_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_schedule_panel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_schedule_panel, lv_color_hex(0x0057A2), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_schedule_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_schedule_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_schedule_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_schedule_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_schedule_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_schedule_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_schedule_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule1 = lv_obj_create(ui_schedule_panel);
  lv_obj_set_width(ui_schedule1, lv_pct(100));
  lv_obj_set_flex_grow(ui_schedule1, 1);
  lv_obj_set_align(ui_schedule1, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_schedule1, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_schedule1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_schedule1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_schedule1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule1, lv_color_hex(0x0057A2), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_schedule1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_schedule1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_schedule1, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_schedule1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_schedule1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_schedule1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_schedule1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_schedule1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_schedule1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_schedule1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_schedule1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule1, lv_color_hex(0x9FC6E8), LV_PART_MAIN | LV_STATE_DISABLED);
  lv_obj_set_style_bg_opa(ui_schedule1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

  ui_schedule1_busnumber1 = lv_label_create(ui_schedule1);
  lv_obj_set_width(ui_schedule1_busnumber1, lv_pct(25));
  lv_obj_set_height(ui_schedule1_busnumber1, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule1_busnumber1, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule1_busnumber1, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule1_busnumber1, "9");
  lv_obj_set_style_text_color(ui_schedule1_busnumber1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule1_busnumber1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule1_busnumber1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule1_busnumber1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule1_destination1 = lv_label_create(ui_schedule1);
  lv_obj_set_height(ui_schedule1_destination1, LV_SIZE_CONTENT); /// 100
  lv_obj_set_flex_grow(ui_schedule1_destination1, 1);
  lv_obj_set_align(ui_schedule1_destination1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_schedule1_destination1, "Linjat");
  lv_obj_set_style_text_color(ui_schedule1_destination1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule1_destination1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule1_destination1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule1_destination1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule1_time1 = lv_label_create(ui_schedule1);
  lv_obj_set_width(ui_schedule1_time1, LV_SIZE_CONTENT);  /// 15
  lv_obj_set_height(ui_schedule1_time1, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule1_time1, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule1_time1, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule1_time1, "~0");
  lv_obj_set_style_text_color(ui_schedule1_time1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule1_time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule1_time1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule1_time1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule2 = lv_obj_create(ui_schedule_panel);
  lv_obj_set_width(ui_schedule2, lv_pct(100));
  lv_obj_set_flex_grow(ui_schedule2, 1);
  lv_obj_set_x(ui_schedule2, 0);
  lv_obj_set_y(ui_schedule2, -1);
  lv_obj_set_align(ui_schedule2, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_schedule2, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_schedule2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_schedule2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_schedule2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule2, lv_color_hex(0x0057A2), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_schedule2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_schedule2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_schedule2, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_schedule2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_schedule2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_schedule2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_schedule2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_schedule2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_schedule2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_schedule2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_schedule2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule2, lv_color_hex(0x9FC6E8), LV_PART_MAIN | LV_STATE_DISABLED);
  lv_obj_set_style_bg_opa(ui_schedule2, 255, LV_PART_MAIN | LV_STATE_DISABLED);

  ui_schedule2_busnumber = lv_label_create(ui_schedule2);
  lv_obj_set_width(ui_schedule2_busnumber, lv_pct(25));
  lv_obj_set_height(ui_schedule2_busnumber, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule2_busnumber, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule2_busnumber, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule2_busnumber, "8");
  lv_obj_set_style_text_color(ui_schedule2_busnumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule2_busnumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule2_busnumber, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule2_busnumber, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule2_destination = lv_label_create(ui_schedule2);
  lv_obj_set_height(ui_schedule2_destination, LV_SIZE_CONTENT); /// 100
  lv_obj_set_flex_grow(ui_schedule2_destination, 1);
  lv_obj_set_align(ui_schedule2_destination, LV_ALIGN_CENTER);
  lv_label_set_text(ui_schedule2_destination, "Arabia");
  lv_obj_set_style_text_color(ui_schedule2_destination, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule2_destination, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule2_destination, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule2_destination, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule2_time = lv_label_create(ui_schedule2);
  lv_obj_set_width(ui_schedule2_time, LV_SIZE_CONTENT);  /// 15
  lv_obj_set_height(ui_schedule2_time, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule2_time, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule2_time, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule2_time, "~9");
  lv_obj_set_style_text_color(ui_schedule2_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule2_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule2_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule2_time, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule3 = lv_obj_create(ui_schedule_panel);
  lv_obj_set_width(ui_schedule3, lv_pct(100));
  lv_obj_set_flex_grow(ui_schedule3, 1);
  lv_obj_set_align(ui_schedule3, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_schedule3, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_schedule3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_schedule3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_schedule3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule3, lv_color_hex(0x0057A2), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_schedule3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_schedule3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_schedule3, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_schedule3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_schedule3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_schedule3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_schedule3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_schedule3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_schedule3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_schedule3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_schedule3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule3, lv_color_hex(0x9FC6E8), LV_PART_MAIN | LV_STATE_DISABLED);
  lv_obj_set_style_bg_opa(ui_schedule3, 255, LV_PART_MAIN | LV_STATE_DISABLED);

  ui_schedule3_busnumber = lv_label_create(ui_schedule3);
  lv_obj_set_width(ui_schedule3_busnumber, lv_pct(25));
  lv_obj_set_height(ui_schedule3_busnumber, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule3_busnumber, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule3_busnumber, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule3_busnumber, "9");
  lv_obj_set_style_text_color(ui_schedule3_busnumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule3_busnumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule3_busnumber, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule3_busnumber, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule3_destination = lv_label_create(ui_schedule3);
  lv_obj_set_height(ui_schedule3_destination, LV_SIZE_CONTENT); /// 100
  lv_obj_set_flex_grow(ui_schedule3_destination, 1);
  lv_obj_set_align(ui_schedule3_destination, LV_ALIGN_CENTER);
  lv_label_set_text(ui_schedule3_destination, "Linjat");
  lv_obj_set_style_text_color(ui_schedule3_destination, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule3_destination, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule3_destination, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule3_destination, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule3_time = lv_label_create(ui_schedule3);
  lv_obj_set_width(ui_schedule3_time, LV_SIZE_CONTENT);  /// 15
  lv_obj_set_height(ui_schedule3_time, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule3_time, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule3_time, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule3_time, "~16:39");
  lv_obj_set_style_text_color(ui_schedule3_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule3_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule3_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule3_time, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule4 = lv_obj_create(ui_schedule_panel);
  lv_obj_set_width(ui_schedule4, lv_pct(100));
  lv_obj_set_flex_grow(ui_schedule4, 1);
  lv_obj_set_align(ui_schedule4, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_schedule4, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_schedule4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_schedule4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_schedule4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule4, lv_color_hex(0x0057A2), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_schedule4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_schedule4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_schedule4, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_schedule4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_schedule4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_schedule4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_schedule4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_schedule4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_schedule4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_schedule4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_schedule4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule4, lv_color_hex(0x9FC6E8), LV_PART_MAIN | LV_STATE_DISABLED);
  lv_obj_set_style_bg_opa(ui_schedule4, 255, LV_PART_MAIN | LV_STATE_DISABLED);

  ui_schedule4_busnumber = lv_label_create(ui_schedule4);
  lv_obj_set_width(ui_schedule4_busnumber, lv_pct(25));
  lv_obj_set_height(ui_schedule4_busnumber, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule4_busnumber, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule4_busnumber, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule4_busnumber, "8");
  lv_obj_set_style_text_color(ui_schedule4_busnumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule4_busnumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule4_busnumber, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule4_busnumber, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule4_destination = lv_label_create(ui_schedule4);
  lv_obj_set_height(ui_schedule4_destination, LV_SIZE_CONTENT); /// 100
  lv_obj_set_flex_grow(ui_schedule4_destination, 1);
  lv_obj_set_align(ui_schedule4_destination, LV_ALIGN_CENTER);
  lv_label_set_text(ui_schedule4_destination, "Arabia");
  lv_obj_set_style_text_color(ui_schedule4_destination, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule4_destination, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule4_destination, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule4_destination, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule4_time = lv_label_create(ui_schedule4);
  lv_obj_set_width(ui_schedule4_time, LV_SIZE_CONTENT);  /// 15
  lv_obj_set_height(ui_schedule4_time, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule4_time, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule4_time, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule4_time, "~16:41");
  lv_obj_set_style_text_color(ui_schedule4_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule4_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule4_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule4_time, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule5 = lv_obj_create(ui_schedule_panel);
  lv_obj_set_width(ui_schedule5, lv_pct(100));
  lv_obj_set_flex_grow(ui_schedule5, 1);
  lv_obj_set_align(ui_schedule5, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_schedule5, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_schedule5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_schedule5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_schedule5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule5, lv_color_hex(0x0057A2), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_schedule5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_schedule5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_schedule5, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_schedule5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_schedule5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_schedule5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_schedule5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_schedule5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_schedule5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_row(ui_schedule5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_schedule5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_schedule5, lv_color_hex(0x9FC6E8), LV_PART_MAIN | LV_STATE_DISABLED);
  lv_obj_set_style_bg_opa(ui_schedule5, 255, LV_PART_MAIN | LV_STATE_DISABLED);

  ui_schedule5_busnumber = lv_label_create(ui_schedule5);
  lv_obj_set_width(ui_schedule5_busnumber, lv_pct(25));
  lv_obj_set_height(ui_schedule5_busnumber, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule5_busnumber, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule5_busnumber, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule5_busnumber, "9");
  lv_obj_set_style_text_color(ui_schedule5_busnumber, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule5_busnumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule5_busnumber, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule5_busnumber, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule5_destination = lv_label_create(ui_schedule5);
  lv_obj_set_height(ui_schedule5_destination, LV_SIZE_CONTENT); /// 100
  lv_obj_set_flex_grow(ui_schedule5_destination, 1);
  lv_obj_set_align(ui_schedule5_destination, LV_ALIGN_CENTER);
  lv_label_set_text(ui_schedule5_destination, "Linjat");
  lv_obj_set_style_text_color(ui_schedule5_destination, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule5_destination, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule5_destination, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule5_destination, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_schedule5_time = lv_label_create(ui_schedule5);
  lv_obj_set_width(ui_schedule5_time, LV_SIZE_CONTENT);  /// 15
  lv_obj_set_height(ui_schedule5_time, LV_SIZE_CONTENT); /// 100
  lv_obj_set_align(ui_schedule5_time, LV_ALIGN_CENTER);
  lv_label_set_long_mode(ui_schedule5_time, LV_LABEL_LONG_CLIP);
  lv_label_set_text(ui_schedule5_time, "~16:51");
  lv_obj_set_style_text_color(ui_schedule5_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_schedule5_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_schedule5_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_schedule5_time, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
}
