// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include <lvgl.h>

#include "ui/ui_helpers.h"
#include "ui/ui_events.h"
#include "ui/icons.h"
    // SCREEN: ui_main_screen
    void ui_main_screen_screen_init(void);
    extern lv_obj_t *ui_main_screen;
    extern lv_obj_t *ui_main_panel;
    extern lv_obj_t *ui_clock_panel;
    extern lv_obj_t *ui_date_label;
    extern lv_obj_t *ui_time_label;
    extern lv_obj_t *ui_weather_panel;
    extern lv_obj_t *ui_weather1;
    extern lv_obj_t *ui_weather1_hour;
    extern lv_obj_t *ui_weather1_icon;
    extern lv_obj_t *ui_weather1_temperature;
    extern lv_obj_t *ui_weather2;
    extern lv_obj_t *ui_weather2_hour;
    extern lv_obj_t *ui_weather2_icon;
    extern lv_obj_t *ui_weather2_temperature;
    extern lv_obj_t *ui_weather3;
    extern lv_obj_t *ui_weather3_hour;
    extern lv_obj_t *ui_weather3_icon;
    extern lv_obj_t *ui_weather3_temperature;
    extern lv_obj_t *ui_weather4;
    extern lv_obj_t *ui_weather4_hour;
    extern lv_obj_t *ui_weather4_icon;
    extern lv_obj_t *ui_weather4_temperature;
    extern lv_obj_t *ui_weather5;
    extern lv_obj_t *ui_weather5_hour;
    extern lv_obj_t *ui_weather5_icon;
    extern lv_obj_t *ui_weather5_temperature;
    extern lv_obj_t *ui_schedule_panel;
    extern lv_obj_t *ui_schedule1;
    extern lv_obj_t *ui_schedule1_busnumber1;
    extern lv_obj_t *ui_schedule1_destination1;
    extern lv_obj_t *ui_schedule1_time1;
    extern lv_obj_t *ui_schedule2;
    extern lv_obj_t *ui_schedule2_busnumber;
    extern lv_obj_t *ui_schedule2_destination;
    extern lv_obj_t *ui_schedule2_time;
    extern lv_obj_t *ui_schedule3;
    extern lv_obj_t *ui_schedule3_busnumber;
    extern lv_obj_t *ui_schedule3_destination;
    extern lv_obj_t *ui_schedule3_time;
    extern lv_obj_t *ui_schedule4;
    extern lv_obj_t *ui_schedule4_busnumber;
    extern lv_obj_t *ui_schedule4_destination;
    extern lv_obj_t *ui_schedule4_time;
    extern lv_obj_t *ui_schedule5;
    extern lv_obj_t *ui_schedule5_busnumber;
    extern lv_obj_t *ui_schedule5_destination;
    extern lv_obj_t *ui_schedule5_time;
    // SCREEN: ui_init_screen
    void ui_init_screen_screen_init(void);
    extern lv_obj_t *ui_init_screen;
    extern lv_obj_t *ui_init_screen_spinner;
    extern lv_obj_t *ui_init_screen_label;
    extern lv_obj_t *ui____initial_actions0;

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
